package authors_pack;
// Generated Apr 10, 2019 11:01:53 PM by Hibernate Tools 4.3.1



/**
 * Authors generated by hbm2java
 */
public class Authors  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer age;

    public Authors() {
    }

    public Authors(String name, Integer age) {
       this.name = name;
       this.age = age;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }




}


